{
 "title": "Kubernetes / System / Horizontal Pod Autoscaler",
 "description": "This is a dashboard for viewing HPA operations",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{container =\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "hpa",
    "label": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{container=\"kube-state-metrics\", namespace=\"$namespace\"}, horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{job=\"kube-state-metrics\",  namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"$hpa\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "HPA Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_condition{horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\", status=\"true\", condition=\"AbleToScale\"}) by (condition)",
     "legendFormat": "AbleToScale"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_condition{horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\", status=\"false\", condition=\"ScalingActive\"}) by (condition)",
     "legendFormat": "ScalingInActive"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_condition{horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\", status=\"true\", condition=\"ScalingLimited\"}) by (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Desired Replicas vs Current Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "kube_hpa_spec_max_replicas{job=\"kube-state-metrics\", hpa=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "kube_hpa_spec_min_replicas{job=\"kube-state-metrics\", hpa=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Min"
    }
   ]
  }
 ]
}